### ISSUE TITLE
Enhancement: component methods in Entity API

### ISSUE THREAD

**Issue by acoppes** [Spy-Shifty/BrokenBricksECS#13]
Some times it could be useful to have methods to add/remove/get components from the Entity itself, and since entities live within the EntityManager it makes sense. Otherwise you have to have always both the Entity and the EntityManager at hand to do something over components. 

I believe other ECS have those and when I used some of them in the past it was really useful.

Something like this:

```
       EntityManager _entityManager;

        public Entity(int id, EntityManager entityManager) {
            this.id = id;
            _entityManager = entityManager;
        }

       // stuff

        public bool HasComponent<T>() where T : IComponent
        {
            return _entityManager.HasComponent<T>(this);
        }

        public void AddComponent<T>(T component) where T : IComponent
        {
            _entityManager.AddComponent<T>(this, component);
        }

        public void RemoveComponent<T>() where T : IComponent
        {
            _entityManager.RemoveComponent<T>(this);
        }

        public T GetComponent<T>() where T : IComponent
        {
            return _entityManager.GetComponent<T>(this);
        }
```

**Comment by acoppes** [comment]
https://github.com/Spy-Shifty/BrokenBricksECS/pull/14

**Comment by Spy-Shifty** [comment]
Well Entity is just a struct with a id of 4Byte and yes it would be usefull and is data only.
So it would violate against the concept. This is a really soft argument, I know. 
But because it is a struct it's copied by value and I have a view copies internally. So each time you access the Entity you need to copy both: the pointer to the EntityManager and the id. 
Well you could say its just 12 Bytes but if you have thousends of entites....
This could cost some performance.

You can easly use the InjectionDependency Attribute to attach the EntityManager to your script
ComponentSystem have a native access (Property) to the EntityManager.

**Comment by acoppes** [comment]
Well, if you want to be pure about it, it makes sense. I will have that in my branch though, I don't believe it will be a problem but if it does, it shouldn't be a problem to change back.

**Comment by Spy-Shifty** [comment]
#14
